---
  env:
    browser: true
    jest: true

  parser: babel-eslint

  extends:
    - 'airbnb-base'
    - 'plugin:react/recommended'

  plugins:
    - jest
    - react

  rules:
    react/jsx-uses-vars: 1
    react/prop-types: 0
