---
- hosts: all
  gather_facts: no

  tasks:
    - apt:
        update_cache: true
        name:
          - python3-pip
      become: true

    - pip:
        name:
          - docker
      become: true
